name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/themiify/custom-theme-zid-fork.git
      
      - name: Fetch upstream
        run: |
          git fetch upstream
      
      - name: Sync fork
        run: |
          git checkout main
          git merge upstream/main
      
      - name: Push changes
        run: |
          git push origin main
