name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # تشغيل المزامنة يوميًا عند منتصف الليل
  workflow_dispatch:  # السماح بتشغيل المزامنة يدويًا من واجهة GitHub Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # جلب كل التاريخ لتجنب مشاكل الدمج

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/zidsa/custom-theme-sample.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "No new changes to merge"

      - name: Push Changes to Fork
        run: |
          git push origin main
