name: Sync from Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # تشغيل يوميًا في منتصف الليل UTC
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # جلب كل التاريخ
          token: ${{ secrets.GH_PAT }}

      - name: 🔧 Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🔗 Add Upstream Repository
        run: |
          git remote add upstream https://github.com/zidsa/custom-theme-sample.git || true
          git fetch upstream

      - name: 🔄 Sync Main Branch
        run: |
          git checkout main
          git merge upstream/main --no-edit  # دمج التحديثات من upstream/main إلى main
          git push origin main  # تحديث الفرع main في المستودع الشخصي

      - name: 🔄 Sync Feature Branches with Main
        run: |
          for branch in $(git branch -r | grep -v 'origin/main' | grep -v 'HEAD' | sed 's/origin\///'); do
            echo "🔹 Checking branch: $branch"
            if [[ "$branch" != "main" && "$branch" != "HEAD" ]]; then
              git checkout -B $branch origin/$branch || continue
              git pull origin $branch || continue
              if git merge main --no-commit --no-ff > /dev/null 2>&1; then
                git commit -m "🚀 Merged main into $branch [automated]" || true
                git push origin $branch
                echo "✅ Updated $branch with latest main"
              else
                git merge --abort || true
                echo "⚠️ No changes to merge in $branch - skipping"
              fi
            fi
          done || true  # تجنب فشل السكريبت بسبب exit code 1
