name: Universal Branch Sync (Safe Merge)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync (leave empty for current)'
        required: false
        default: ''

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: 🔧 Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🔗 Add Upstream Repository
        run: |
          git remote add upstream https://github.com/zidsa/custom-theme-sample.git || true
          git fetch upstream

      - name: 🔄 Safe Merge Upstream into Main
        run: |
          git checkout main || git checkout -B main origin/main
          git pull origin main
          git merge upstream/main || true
          git push origin main

      - name: 🔍 Determine Current Branch
        id: branch
        run: |
          echo "branch_name=$(git symbolic-ref --short HEAD)" >> $GITHUB_OUTPUT

      - name: 📢 Notify Success
        if: success()
        run: |
          echo "✅ Branch sync (safe merge) completed successfully on branch: ${{ steps.branch.outputs.branch_name }}."

      - name: ❌ Notify Failure
        if: failure()
        run: |
          echo "❗ Branch sync failed!"
