name: Sync Main with Upstream (Zid)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # تشغيل تلقائي كل يوم

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # جلب كل الفروع

      - name: 🔧 Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 🔗 Add Upstream Repository
        run: |
          git remote add upstream https://github.com/USERNAME/REPO.git || echo "Upstream already exists"
          git fetch upstream

      - name: 🔄 Sync Main with Upstream (Zid)
        run: |
          git fetch --all
          git checkout -B main origin/main 2>/dev/null || git checkout main
          git reset --hard upstream/main
          git pull upstream main --rebase --autostash || git rebase --abort
          git push origin main --force

      - name: 🛠 Determine Current Branch
        run: git branch --show-current

      - name: 🔄 Sync Feature Branches with Main
        run: |
          for branch in $(git branch -r | grep -vE 'main|HEAD' | sed 's/origin\///'); do
            git checkout $branch
            git rebase main || git rebase --abort
            git push origin $branch --force
          done

      - name: ✅ Complete job
        run: echo "Sync completed successfully!"
