name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # يقوم بالمزامنة يوميًا
  workflow_dispatch: # يتيح التشغيل اليدوي

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/zidsa/custom-theme-sample.git
          git fetch upstream

      - name: Fetch and Merge Upstream Changes
        run: |
          git checkout main
          git merge --allow-unrelated-histories upstream/main -m "Sync with upstream"

      - name: Push Changes to Fork
        run: |
          git push origin main
